/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PThlDfdHWl1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function CampaingListPage() {
  return (
    (<div
      className="grid max-w-5xl gap-6 px-4 mx-auto lg:px-6 md:grid-cols-2 lg:grid-cols-3">
      <div
        className="flex flex-col rounded-lg overflow-hidden border border-gray-200 shadow-sm cursor-pointer hover:scale-105 transition-transform dark:border-gray-800 dark:border-gray-800">
        <div className="relative">
          <img
            alt="Campaign"
            className="aspect-[2/3] object-cover"
            height="400"
            src="/placeholder.svg"
            width="600" />
          <Badge className="absolute top-4 start-4" color="blue">
            Featured
          </Badge>
        </div>
        <div className="flex-1 grid gap-2 p-4">
          <h3 className="text-xl font-semibold tracking-tight">Clean Water Initiative</h3>
          <p className="text-sm line-clamp-3">Help us provide clean and safe drinking water to communities in need.</p>
        </div>
        <div className="grid w-full p-4 border-t items-center">
          <Button className="w-full justify-start" variant="outline">
            View Campaign
          </Button>
        </div>
      </div>
      <div
        className="flex flex-col rounded-lg overflow-hidden border border-gray-200 shadow-sm cursor-pointer hover:scale-105 transition-transform dark:border-gray-800 dark:border-gray-800">
        <div className="relative">
          <img
            alt="Campaign"
            className="aspect-[2/3] object-cover"
            height="400"
            src="/placeholder.svg"
            width="600" />
        </div>
        <div className="flex-1 grid gap-2 p-4">
          <h3 className="text-xl font-semibold tracking-tight">School Supplies Drive</h3>
          <p className="text-sm line-clamp-3">
            Support our initiative to provide children with the tools they need to learn.
          </p>
        </div>
        <div className="grid w-full p-4 border-t items-center">
          <Button className="w-full justify-start" variant="outline">
            View Campaign
          </Button>
        </div>
      </div>
      <div
        className="flex flex-col rounded-lg overflow-hidden border border-gray-200 shadow-sm cursor-pointer hover:scale-105 transition-transform dark:border-gray-800 dark:border-gray-800">
        <div className="relative">
          <img
            alt="Campaign"
            className="aspect-[2/3] object-cover"
            height="400"
            src="/placeholder.svg"
            width="600" />
        </div>
        <div className="flex-1 grid gap-2 p-4">
          <h3 className="text-xl font-semibold tracking-tight">Food for All Program</h3>
          <p className="text-sm line-clamp-3">Your donations will help us feed the hungry in our communities.</p>
        </div>
        <div className="grid w-full p-4 border-t items-center">
          <Button className="w-full justify-start" variant="outline">
            View Campaign
          </Button>
        </div>
      </div>
      <div
        className="flex flex-col rounded-lg overflow-hidden border border-gray-200 shadow-sm cursor-pointer hover:scale-105 transition-transform dark:border-gray-800 dark:border-gray-800">
        <div className="relative">
          <img
            alt="Campaign"
            className="aspect-[2/3] object-cover"
            height="400"
            src="/placeholder.svg"
            width="600" />
        </div>
        <div className="flex-1 grid gap-2 p-4">
          <h3 className="text-xl font-semibold tracking-tight">Shelter for All Initiative</h3>
          <p className="text-sm line-clamp-3">Help us provide safe and secure shelters for the homeless.</p>
        </div>
        <div className="grid w-full p-4 border-t items-center">
          <Button className="w-full justify-start" variant="outline">
            View Campaign
          </Button>
        </div>
      </div>
      <div
        className="flex flex-col rounded-lg overflow-hidden border border-gray-200 shadow-sm cursor-pointer hover:scale-105 transition-transform dark:border-gray-800 dark:border-gray-800">
        <div className="relative">
          <img
            alt="Campaign"
            className="aspect-[2/3] object-cover"
            height="400"
            src="/placeholder.svg"
            width="600" />
        </div>
        <div className="flex-1 grid gap-2 p-4">
          <h3 className="text-xl font-semibold tracking-tight">Healthcare Access Project</h3>
          <p className="text-sm line-clamp-3">
            Your support will help us provide healthcare services to underserved communities.
          </p>
        </div>
        <div className="grid w-full p-4 border-t items-center">
          <Button className="w-full justify-start" variant="outline">
            View Campaign
          </Button>
        </div>
      </div>
    </div>)
  );
}
