/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WD7TZGM2gMo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { CardContent, Card } from "@/components/ui/card"
import { Switch } from "@/components/ui/switch"

export function SettingPage({ church }) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 md:gap-3" >
      <Card className="w-full max-w-3xl">
        <header className="px-6 py-8">
          <div className="flex flex-col justify-center">
            <img
              alt="Profile picture"
              height="200"
              src={church.logo}
              width="200" />
            <div className="mt-3 p-0">
              <h1 className="text-2xl font-bold leading-none">{church.name}</h1>
              <p className="text-gray-500 text-sm dark:text-gray-400">{church.address}</p>
              <p className="text-gray-500 text-sm dark:text-gray-400">{church.phone}</p>
              <p className="text-gray-500 text-sm dark:text-gray-400">{church.email}</p>
              

            </div>
          </div>
        </header>
        <CardContent className="px-6 py-2">
          <div className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" value={church.name} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" value={church.email} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Adresse</Label>
              <Input id="email" value={church.address} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input id="password" placeholder="Password" type="password" value="*******************" />
            </div>
          </div>
        </CardContent>
        <CardContent className="px-6 py-8">
          <div className="space-y-6">
            <div className="grid grid-cols-2 items-center gap-4">
              <div>
                <h3 className="text-lg font-medium leading-none">Double facteur</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Ajoutez une couche de sécurité supplémentaire à votre compte.
                </p>
              </div>
              <Switch id="2fa" />
            </div>
          </div>
        </CardContent>
      </Card>
      <Card className="w-full max-h-[25rem] max-w-3xl">
        <h3 className="text-2xl font-semibold text-gray-800 mx-4 mt-4">Information Bancaire</h3>
        <p className="text-xs text-gray-500 px-4">Utile pour le versement des fonds percu sur la plateforme</p>
        <CardContent className="px-6 py-8">
          <div className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="name">Intitulé du Compte</Label>
              <Input id="name" value="" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="name">Numéro de Compte</Label>
              <Input id="name" value="" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">SWIFT</Label>
              <Input id="email" value="" />
            </div>
          </div>
        </CardContent>

      </Card>
    </div>
  );
}
